name: Send Notification

on:
  # Runs at 10:00 UTC every day
  schedule:
    - cron:  '0 10 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Should Notify
        id: should-notify
        run: |
          SHOULD="true"
          echo "should=$SHOULD" >> $GITHUB_OUTPUT

      - name: Discord notification
        if: steps.should-notify.outputs.should == 'true'
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@0.3.2
        with:
          args: 'The project {{ EVENT_PAYLOAD.repository.full_name }} has been deployed.'
