name: Send Notification

on:
  # Runs every 5 minutes
  schedule:
    - cron:  '*/5 * * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Should Notify
        id: should-notify
        run: |
          OUTPUT=$(curl -s -o /dev/null -w "%{http_code}" https://landscape.kramden.org/)
          if [ $OUTPUT == 200 ]; then
            SHOULD="true"
          else
            SHOULD="false"
          fi
          echo "should=$SHOULD" >> $GITHUB_OUTPUT

      - name: Discord notification
        if: steps.should-notify.outputs.should == 'true'
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USERNAME: "Kramden Monitor"
        uses: Ilshidur/action-discord@0.3.2
        with:
          args: 'The Landscape Server is down at https://landscape.kramden.org'
